---
- name: "Installation et mise en place d'un cluster Wildfly"
  hosts: "{{ wildfly_ansible_hosts | default('localhost') }}"
  gather_facts: true
  vars:
    wfly_version: 16.0.0.Final
    workdir: /opt/wildfly/
    wfly_zipfile: "wildfly-{{ wfly_version }}.zip"
    wfly_download_url: https://download.jboss.org/wildfly/{{ wfly_version }}/{{ wfly_zipfile }}
    wildfly:
      home: "{{ workdir }}/wildfly-{{ wfly_version }}/"
      user: wildfly
      basedir_prefix: /run/wfly-
      base_config: standalone-ha.xml
      config_name_prefix: wfly-
      bind_addr: 127.0.0.1
    app_url: http://people.redhat.com/~rpelisse/simple-webapp-1.1.war
    app_path: /tmp/simple-webapp-1.1.war
    app_name: simple-webapp-1.1.war
  collections:
    - wildfly.jcliff
  roles:
    - jcliff
  tasks:

  - name: "Installation des dépendances de Wildfly"
    yum:
      name: "{{ item }}"
      state: latest
    loop:
     - zip
     - unzip
     - java-1.8.0-openjdk-devel

  - name: "Création de l'utilisateur {{ wildfly.user }}"
    user:
      name: "{{ wildfly.user }}"
      comment: "Utilisateur associé Wildfly"

  - name: "Création du répertoire JBOSS_HOME: {{ jboss_home }}"
    file:
      path: "{{ workdir }}"
      state: directory
      owner: "{{ wildfly.user }}"
      group: "{{ wildfly.user }}"
      mode: '0755'

  - name: "Téléchargement et décompression de l'archive Wildfly depuis {{ wfly_download_url }}"
    unarchive:
      src: "{{ wfly_download_url }}"
      dest: "{{ workdir }}"
      owner: "{{ wildfly.user }}"
      group: "{{ wildfly.user }}"
      remote_src: 'yes' 
      creates: "{{ wildfly.home }}"

  - name: "Download a demo app to deploy"
    get_url:
      url: "{{ app_url }}"
      dest: "{{ app_path }}"

  - name: "Mise en place des trois instances de Wildfly"
    include_tasks: tasks/setup_instance.yml
    loop:
      - 1
      - 2
      - 3
